site_name: GCP Ingestion
site_description: Mozilla Telemetry ingestion on Google Cloud Platform
site_author: Mozilla Data Platform Team

repo_url: https://github.com/mozilla/gcp-ingestion/
edit_uri: blob/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
  palette:
    primary: teal

plugins:
  - search
  - awesome-pages

nav:
  - Home: index.md
  - Architecture:
    - Overview: architecture/overview.md
    - ... | architecture/*.md
  - ingestion-edge:
    - Overview: ingestion-edge/index.md
    - ... | ingestion-edge/*
  - ingestion-beam:
    - Overview: ingestion-beam/index.md
    - ... | ingestion-beam/*
  - ingestion-sink:
    - Overview: ingestion-sink/index.md
    - ... | ingestion-sink/*
  - ...
